### ISSUE TITLE
[Ceci n'est pas une issue] Thanks a lot!

### ISSUE THREAD

**Issue by jibe-b** [askomics/askomics.github.io#1]
I am looking forward to playing with askomics and try to push it to its limits :)

Thanks for having developped it!

**Comment by xgaia** [comment]
Hello @jibe-b , thanks for your feedback.

This repo is for the askomics website. Can you please move your issues to the [askomics](https://github.com/askomics/askomics/issues) repository ?

**Comment by jibe-b** [comment]
Oups, three times the same error ;)
